version: '3.5'
services:
  angular-service:
    container_name: itjuana-client
    build: ./client
    volumes:
      - './client:/usr/src/app' 
    ports: 
      - '4200:4200'
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
  db:
    container_name: itjuana-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'itjuana'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3310:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
  ktor-backend:
    container_name: itjuana-backend
    build: ./ktor
    volumes:
      - './ktor:/usr/src/app-backend' 
    ports: 
      - '8081:8080'
volumes:
  db: